# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3ec176034a83eb7ded6bbc19fd1b56f5176c98f3d9d366bdb289323c2a46ca29f91ebd05bd96e6ef502dc434e854984cc30014b47f7a98161bb5ae62980a6d2

test:
  secret_key_base: 1b28a64aaa8ca7897f8d4ad93c095c8a6eab133f91f7de79e1a9d011f93d17b5b8227bbe1affa8af52901ab0c57f5cffad7c1da4046f16751f3cc6dda18454a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
