# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f49fc5fef8562f6d24693bfb4e04de00a374342e2a1a4c3fad1696d1a972bf0decbeae6927b53544e7c4c0a8197c7e9c39479cbc8daa5e51c299e952e49cd65

test:
  secret_key_base: ecb098879df6aa1a39ac3a1a20779406235f338425df861c466cef2981fba0b6dc855d26f48069fce3cc7a56ccda5d52a137a6377498021b31b935cb3dd8db4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
