# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b776ecb0bef8fec74d9286f1d8c4e7a8a8803e035b0401580eb0c46103f8d3fa96804a1dcc3a57acca7df844cb29466e1e783a93c05ba545da1d890dc780e3ea

test:
  secret_key_base: 00319a685256eeb7d0ea88a09ac2a7b4a11f848dce805440bfa13f6eeb34eb27d3b6d0b0ad62669eb6769f5c624c4aa315e23b47d10daa716fceb16ca1c0a0e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
