# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16fcb3aa0fb6ffdff4a74598f2b27ab89b63f5196d1f15db87dd86023c5046815d99a03f399c4a432f27c927f48aa465133a55c8e3a72575e79de160f547ada8

test:
  secret_key_base: 214861679d5f7354350b8789a1b8f667d37990842e6bbb554adf2354acea8630b329e7d0be3688317c8a52a66cc47116dc77d502cf8bf73338880a0124ba3a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
